### ISSUE TITLE
Support for not hidden salesforcedx.yml

### ISSUE THREAD

**Issue by cwallsfdc** [wadewegner/salesforce-dx-buildpack#12]
`salesforcedx.yml` is an important project file.  Let's not hide.

To support existing `.salesforcedx.yml`, we could look for `salesforcedx.yml` then `.salesforcedx.yml`.

**Comment by wadewegner** [comment]
I propose we replace this issue with https://github.com/wadewegner/salesforce-dx-buildpack/issues/5. I think `sfdx.yml` is better than `salesforcedx.yml`, and if we're going to rename it I'd rather do it once.
