### ISSUE TITLE
Test updates

### ISSUE THREAD

**Issue by cwallsfdc** [wadewegner/salesforce-dx-buildpack#14]
- Heroku CI test output needs to be TAP only, so (a) don't call `set -x` and (b) remove `apex-test-format` s output must be TAP.
- Clean-up test orgs (w/ option to retain)

**Comment by cwallsfdc** [comment]
https://github.com/wadewegner/salesforce-dx-buildpack/pull/16

**Comment by wadewegner** [comment]
Good stuff!
