### ISSUE TITLE
Destroy scratch orgs when review app is deleted

### ISSUE THREAD

**Issue by wadewegner** [wadewegner/salesforce-dx-buildpack#2]
https://devcenter.heroku.com/articles/github-integration-review-apps#pr-predestroy-script

Setup a script to destroy review apps

**Comment by wadewegner** [comment]
@cwallsfdc

**Comment by cwallsfdc** [comment]
Also, if RA fails post-org-create, we should delete scratch org.

**Comment by wadewegner** [comment]
@cwallsfdc Here: https://github.com/wadewegner/salesforce-dx-buildpack/issues/7

**Comment by wadewegner** [comment]
I believe @cwallsfdc you fixed it here: https://github.com/wadewegner/salesforce-dx-buildpack/pull/18

I confirmed that the destroyed RA also deleted the scratch org. I feel good closing this and will unless anyone pushes back.
